cat << 'EOF' > starter/backend/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 509692709711.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:715fccbfa5d684be88cd414cd8caa077b02d5b1e
          ports:
            - containerPort: 5000
EOF